language: rust
sudo: required
services:
  - docker
matrix:
  include:
    - branches:
        only:
          - master
      script:
        - chmod -R 777 .
        - ./build.sh
        - ./publish.sh
    - branches:
        only:
          - dev
      script:
        - cargo test