language: rust
sudo: required
cache: cargo
services:
  - docker
script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then cargo test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then chmod -R 777 .; ./build.sh; ./publish.sh; fi